/**
 * IA Loop — real git operations.
 *
 * All git access goes through here so the orchestrator collects the repository
 * state itself instead of trusting what a model claims it changed.
 *
 * Read helpers are safe by construction. The only mutating operation is
 * `createWorktree`, which refuses to force, reset or delete anything.
 */

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { access } from 'node:fs/promises';
import { join } from 'node:path';

import { SpikeError } from './claude-process.mjs';

const execFileAsync = promisify(execFile);

/**
 * Paths regenerated by tooling. Their dirtiness is expected and does not block;
 * anything else dirty does.
 */
export const REGENERATED_PATHS = Object.freeze(['graphify-out']);

/** Runs git, returning trimmed stdout. Throws SpikeError on failure. */
export async function git(args, { cwd, timeoutMs = 120_000, maxBuffer = 64 * 1024 * 1024 } = {}) {
  try {
    const { stdout } = await execFileAsync('git', args, { cwd, timeout: timeoutMs, maxBuffer });
    return stdout.trim();
  } catch (error) {
    throw new SpikeError('GIT_FAILED', `git ${args.slice(0, 3).join(' ')} failed: ${error.message}`, {
      args,
      cwd,
    });
  }
}

/** Same, but returns null instead of throwing — for existence probes. */
async function gitOrNull(args, options) {
  try {
    return await git(args, options);
  } catch {
    return null;
  }
}

export function createGitProbe(repoRoot) {
  return {
    repoRoot,

    currentBranch() {
      return git(['rev-parse', '--abbrev-ref', 'HEAD'], { cwd: repoRoot });
    },

    head() {
      return git(['rev-parse', 'HEAD'], { cwd: repoRoot });
    },

    /**
     * Dirtiness excluding regenerated paths.
     *
     * The exclusion is delegated to git rather than parsed by column offset:
     * trimming git's output eats the leading status space of the first line.
     */
    async isDirty() {
      const status = await git(
        ['status', '--porcelain', '--', '.', ...REGENERATED_PATHS.map((p) => `:(exclude)${p}`)],
        { cwd: repoRoot },
      );
      return status !== '';
    },

    async relevantDirtyFiles() {
      const status = await git(
        ['status', '--porcelain', '--', '.', ...REGENERATED_PATHS.map((p) => `:(exclude)${p}`)],
        { cwd: repoRoot },
      );
      return status === '' ? [] : status.split('\n').map((l) => l.slice(3)).filter(Boolean);
    },

    async branchExists(name) {
      return (await gitOrNull(['rev-parse', '--verify', `refs/heads/${name}`], { cwd: repoRoot })) !== null;
    },

    async commitExists(sha) {
      return (await gitOrNull(['rev-parse', '--verify', `${sha}^{commit}`], { cwd: repoRoot })) !== null;
    },

    async worktrees() {
      const out = await git(['worktree', 'list', '--porcelain'], { cwd: repoRoot });
      const entries = [];
      let current = null;
      for (const line of out.split('\n')) {
        if (line.startsWith('worktree ')) {
          if (current) entries.push(current);
          current = { path: line.slice('worktree '.length), branch: null };
        } else if (line.startsWith('branch ') && current) {
          current.branch = line.slice('branch '.length);
        }
      }
      if (current) entries.push(current);
      return entries;
    },

    async pathExists(relPath) {
      try {
        await access(join(repoRoot, relPath));
        return true;
      } catch {
        return false;
      }
    },
  };
}

/**
 * Collects the REAL change surface of a worktree against a base commit.
 *
 * Deliberately not taken from the model's own report: the repository is the
 * authority on what changed.
 */
export async function collectWorktreeChanges(worktreePath, baseSha, { maxDiffBytes = 4 * 1024 * 1024 } = {}) {
  const opts = { cwd: worktreePath };

  const head = await git(['rev-parse', 'HEAD'], opts);
  const branch = await git(['rev-parse', '--abbrev-ref', 'HEAD'], opts);
  const status = await git(['status', '--porcelain'], opts);

  // Commits the base does not have. Must stay empty: the Developer may not commit.
  const commitsRaw = await git(['log', '--oneline', `${baseSha}..HEAD`], opts);
  const commits = commitsRaw === '' ? [] : commitsRaw.split('\n');

  // Tracked changes against the base, plus untracked files, which a diff misses.
  const trackedRaw = await git(['diff', '--name-only', baseSha, '--'], opts);
  const tracked = trackedRaw === '' ? [] : trackedRaw.split('\n').filter(Boolean);

  const untrackedRaw = await git(['ls-files', '--others', '--exclude-standard'], opts);
  const untracked = untrackedRaw === '' ? [] : untrackedRaw.split('\n').filter(Boolean);

  const changedFiles = [...new Set([...tracked, ...untracked])].sort();
  const diffStat = await git(['diff', '--stat', baseSha, '--'], opts);

  let diff = await git(['diff', baseSha, '--'], opts, { maxBuffer: maxDiffBytes });
  let diffTruncated = false;
  if (diff.length > maxDiffBytes) {
    diff = diff.slice(0, maxDiffBytes);
    diffTruncated = true;
  }

  return {
    base: baseSha,
    head,
    branch,
    changedFiles,
    untracked,
    commits,
    diffStat,
    diff,
    diffTruncated,
    statusPorcelain: status,
    clean: status === '' && changedFiles.length === 0,
  };
}

/**
 * A cheap fingerprint of the worktree's content, used to prove the reviewer did
 * not modify anything.
 */
export async function worktreeFingerprint(worktreePath) {
  const opts = { cwd: worktreePath };
  const head = await git(['rev-parse', 'HEAD'], opts);
  const status = await git(['status', '--porcelain'], opts);
  // Hashes staged+unstaged content of tracked files.
  const treeHash = await git(['stash', 'create'], opts).catch(() => '');
  return { head, status, treeHash };
}

/**
 * Creates the worktree for real.
 *
 * Only ever runs `git worktree add -b <branch> <path> <base>`. No force, no
 * reset, no delete, no checkout of the main working copy.
 */
export async function createWorktree({ repoRoot, path, branch, base }) {
  if (!repoRoot || !path || !branch || !base) {
    throw new SpikeError('INVALID_ARGS', 'repoRoot, path, branch and base are required');
  }

  const output = await git(['worktree', 'add', '-b', branch, path, base], {
    cwd: repoRoot,
    timeoutMs: 300_000,
  });

  const created = join(repoRoot, path);
  const head = await git(['rev-parse', 'HEAD'], { cwd: created });
  const createdBranch = await git(['rev-parse', '--abbrev-ref', 'HEAD'], { cwd: created });

  if (head !== base) {
    throw new SpikeError(
      'WORKTREE_HEAD_MISMATCH',
      `Worktree HEAD ${head} does not match the requested base ${base}`,
    );
  }
  if (createdBranch !== branch) {
    throw new SpikeError(
      'WORKTREE_BRANCH_MISMATCH',
      `Worktree is on branch ${createdBranch}, expected ${branch}`,
    );
  }

  return { path: created, branch: createdBranch, head, output };
}
