#!/usr/bin/env node
/**
 * IA Loop — orchestrator entry point.
 *
 *   npm run ia-loop:goal -- 003 --dry-run
 *
 * The orchestrator is the ONLY component that decides who works next. The
 * models never call each other: every hand-off is validated and recorded here.
 *
 * V2 supports --dry-run only. A dry run:
 *   - discovers and validates the Goal against the migration artefacts
 *   - records the two distinct baselines
 *   - plans the worktree WITHOUT creating it
 *   - health-checks the workers
 *   - publishes NO job and calls NO model
 */

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { access } from 'node:fs/promises';

import { SpikeError } from './lib/claude-process.mjs';
import { createJobStore } from './lib/job-store.mjs';
import { discoverGoal } from './lib/goal-discovery.mjs';
import { planWorktree } from './lib/worktree-manager.mjs';
import { readWorkerHealth, WORKER_HEALTH, SESSION_STRATEGY } from './lib/worker-registry.mjs';
import { LOOP_STATES, createLoopStateMachine } from './lib/loop-state.mjs';

const execFileAsync = promisify(execFile);
const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..');
const STATE_DIR = join(HERE, '.state');

const TECH_LEAD_MODEL = process.env.IA_LOOP_TECH_LEAD_MODEL ?? 'claude-fable-5-1';
const DEVELOPER_MODEL = process.env.IA_LOOP_DEVELOPER_MODEL ?? 'claude-opus-5';
const REVIEW_LEVEL = 'DEEP';

async function git(args) {
  const { stdout } = await execFileAsync('git', args, { cwd: REPO_ROOT, timeout: 60_000 });
  return stdout.trim();
}

/**
 * Paths regenerated by tooling (graphify hooks rewrite these on every commit).
 * Their dirtiness is expected and is not a reason to block a worktree plan.
 * Anything else dirty still blocks.
 */
const REGENERATED_PATHS = ['graphify-out'];

/** Read-only git probes injected into the worktree planner. */
const gitProbe = {
  async currentBranch() {
    return git(['rev-parse', '--abbrev-ref', 'HEAD']);
  },
  async isDirty() {
    // The exclusion is delegated to git rather than parsed by column offset:
    // `git()` trims its output, which would eat the leading status space of the
    // first porcelain line and shift every slice by one.
    const status = await git([
      'status', '--porcelain', '--', '.',
      ...REGENERATED_PATHS.map((p) => `:(exclude)${p}`),
    ]);
    return status !== '';
  },
  async branchExists(name) {
    try {
      await git(['rev-parse', '--verify', `refs/heads/${name}`]);
      return true;
    } catch {
      return false;
    }
  },
  async worktrees() {
    const out = await git(['worktree', 'list', '--porcelain']);
    const entries = [];
    let current = null;
    for (const line of out.split('\n')) {
      if (line.startsWith('worktree ')) {
        if (current) entries.push(current);
        current = { path: line.slice('worktree '.length), branch: null };
      } else if (line.startsWith('branch ') && current) {
        current.branch = line.slice('branch '.length);
      }
    }
    if (current) entries.push(current);
    return entries;
  },
  async pathExists(relPath) {
    try {
      await access(join(REPO_ROOT, relPath));
      return true;
    } catch {
      return false;
    }
  },
};

async function resolveSha(sha) {
  try {
    await git(['rev-parse', '--verify', `${sha}^{commit}`]);
    return true;
  } catch {
    return false;
  }
}

function parseArgs(argv) {
  const args = argv.slice(2);
  const goalId = args.find((a) => /^\d{3}$/.test(a));
  const dryRun = args.includes('--dry-run');

  if (!goalId) {
    throw new SpikeError('INVALID_ARGS', 'Usage: npm run ia-loop:goal -- <goalId> --dry-run  (e.g. 003)');
  }
  if (!dryRun) {
    // Real execution is not implemented in V2 and must not happen by omission.
    throw new SpikeError(
      'DRY_RUN_REQUIRED',
      'V2 supports --dry-run only. Real Goal execution is a separate, explicit step that has not been authorised yet.',
    );
  }
  return { goalId, dryRun };
}

function formatHealth(health) {
  if (health.health === WORKER_HEALTH.OFFLINE) return 'OFFLINE (worker not running)';
  const age = health.ageMs === null ? '?' : `${Math.round(health.ageMs / 1000)}s ago`;
  return `${health.health} (state ${health.state}, heartbeat ${age})`;
}

async function main() {
  const out = [];
  const emit = (line = '') => out.push(line);

  const { goalId } = parseArgs(process.argv);
  const store = createJobStore(STATE_DIR);
  const machine = createLoopStateMachine();

  emit('IA Loop — Goal Runner');
  emit('');
  emit(`Mode:\nDRY_RUN`);
  emit('');

  // --- Goal discovery ------------------------------------------------------
  const goal = await discoverGoal({ repoRoot: REPO_ROOT, goalId, resolveSha });
  machine.transitionTo(LOOP_STATES.GOAL_READY, { goal: goal.goalId });

  emit('Goal discovery:');
  emit('PASS');
  emit(`  goal: ${goal.goalId} — ${goal.title}`);
  emit(`  status: ${goal.status}`);
  emit(`  path: ${goal.goalPath.replace(REPO_ROOT, '.').replace(/\\/g, '/')}`);
  emit(`  previous goal: ${goal.previousGoalId ?? 'n/a'} (${goal.previousGoalStatus ?? 'n/a'})`);
  emit('');

  // --- The two baselines ---------------------------------------------------
  // These are different by design and must never be collapsed: the accepted
  // baseline is what the functional diff stays traceable against, while the
  // execution base is the tree that also carries Goal docs and this tooling.
  const executionBase = await git(['rev-parse', 'HEAD']);

  emit('Migration baseline (accepted):');
  emit(`  ${goal.migrationAcceptedBaseline}`);
  emit('Execution base (current HEAD):');
  emit(`  ${executionBase}`);
  emit(`  distinct from accepted baseline: ${executionBase !== goal.migrationAcceptedBaseline ? 'YES (expected)' : 'NO'}`);
  emit('');

  // --- Agents --------------------------------------------------------------
  emit('Tech Lead:');
  emit(`  ${TECH_LEAD_MODEL}`);
  emit(`  ${SESSION_STRATEGY.PERSISTENT}`);
  emit('Developer:');
  emit(`  ${DEVELOPER_MODEL}`);
  emit(`  ${SESSION_STRATEGY.STATELESS}`);
  emit('');

  // --- Worktree plan -------------------------------------------------------
  machine.transitionTo(LOOP_STATES.PREPARING_WORKTREE);
  const plan = await planWorktree({ goalId, executionBase, git: gitProbe });

  emit('Worktree plan:');
  emit(`  path: ${plan.path}`);
  emit(`  branch: ${plan.branch}`);
  emit(`  base: ${plan.executionBase}`);
  emit(`  current branch (untouched): ${plan.currentBranch}`);
  emit(`  planned command: ${plan.plannedCommand}`);
  emit(`  created: NO (dry run)`);
  if (plan.blockers.length > 0) {
    emit('  blockers:');
    for (const blocker of plan.blockers) emit(`    - [${blocker.code}] ${blocker.message}`);
  } else {
    emit('  blockers: none');
  }
  emit('');

  if (plan.safe) {
    machine.transitionTo(LOOP_STATES.WORKTREE_READY);
  }

  // --- Workers -------------------------------------------------------------
  const [techLeadHealth, developerHealth] = await Promise.all([
    readWorkerHealth(store, 'tech_lead'),
    readWorkerHealth(store, 'developer'),
  ]);

  emit('Workers:');
  emit(`  tech-lead: ${formatHealth(techLeadHealth)}`);
  emit(`  developer: ${formatHealth(developerHealth)}`);
  emit('');

  emit('Review:');
  emit(`  ${REVIEW_LEVEL}`);
  emit('');

  // --- Persist the run snapshot -------------------------------------------
  await store.writeCurrentGoal({
    goalId: goal.goalId,
    title: goal.title,
    status: goal.status,
    goalPath: goal.goalPath,
    migrationAcceptedBaseline: goal.migrationAcceptedBaseline,
    executionBase,
  });
  await store.writeRuntime({
    mode: 'DRY_RUN',
    goal: goal.goalId,
    state: machine.state,
    migrationAcceptedBaseline: goal.migrationAcceptedBaseline,
    executionBase,
    worktreePlan: { path: plan.path, branch: plan.branch, safe: plan.safe },
    reviewLevel: REVIEW_LEVEL,
    goalExecuted: false,
  });
  await store.appendEvent({
    type: 'DRY_RUN_COMPLETED',
    goal: goal.goalId,
    state: machine.state,
    worktreeSafe: plan.safe,
  });

  emit('State:');
  for (const t of machine.history) emit(`  ${t.from} -> ${t.to}`);
  emit(`  current: ${machine.state}`);
  emit('');

  // A dry run must never publish a job or call a model. Asserted, not assumed.
  const publishedDeveloperJobs = await store.listJobs('developer');
  const publishedReviewJobs = await store.listJobs('tech_lead');

  emit('Dry-run guarantees:');
  emit(`  developer jobs published: ${publishedDeveloperJobs.length}`);
  emit(`  review jobs published: ${publishedReviewJobs.length}`);
  emit('  model calls: 0');
  emit('  worktree created: NO');
  emit('');

  emit('Goal executed:');
  emit('NO');
  emit('');

  const workersReady = techLeadHealth.health === WORKER_HEALTH.RUNNING
    && developerHealth.health === WORKER_HEALTH.RUNNING;

  // Worker health is reported but does not gate the dry run: the point is to
  // validate discovery, baselines and the plan, which hold whether or not the
  // two terminals happen to be open.
  const passed = goal.status === 'READY'
    && executionBase !== goal.migrationAcceptedBaseline
    && publishedDeveloperJobs.length === 0
    && publishedReviewJobs.length === 0;

  emit('Overall:');
  emit(passed ? 'PASS' : 'FAIL');
  if (!workersReady) {
    emit('');
    emit('Note: one or both workers are not running. Open them in two terminals to see the full picture:');
    emit('  npm run ia-loop:tech-lead');
    emit('  npm run ia-loop:developer');
  }

  console.log(out.join('\n'));
  return passed ? 0 : 1;
}

main()
  .then((code) => { process.exitCode = code; })
  .catch((error) => {
    const code = error instanceof SpikeError ? error.code : 'UNEXPECTED_ERROR';
    console.error(`IA Loop — Goal Runner\n\nBlocker: [${code}] ${error.message}\n\nOverall:\nFAIL`);
    process.exitCode = 1;
  });
